{{- if .Values.aiWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.fullname" . }}-ai-worker
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ai-worker
    {{- with .Values.aiWorker.deploymentLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- with .Values.aiWorker.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  replicas: {{ .Values.aiWorker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nextcloud.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ai-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nextcloud.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ai-worker
        {{- with .Values.aiWorker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.aiWorker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        {{- toYaml .Values.aiWorker.affinity | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.aiWorker.securityContext | nindent 8 }}
      podSecurityContext:
        {{- toYaml .Values.aiWorker.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-service
          image: {{ .Values.aiWorker.image.repository }}:{{ .Values.aiWorker.image.tag }}
          command:
            - sh
            - -c
            - >-
              until curl -sf {{- if .Values.aiWorker.useHostName }}https://{{ .Values.nextcloud.host }}/status.php{{- else }}http://{{ template "nextcloud.fullname" . }}:{{ .Values.service.port }}/status.php{{- end }};
              do echo waiting for service; sleep 5;
              done
      containers:
        - name: nextcloud-aiworker
          image: {{ include "nextcloud.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - |-
              set -e; while true; do php occ background-job:worker -v -t 60 "OC\TaskProcessing\SynchronousBackgroundJob"; done
          resources:
            {{- toYaml .Values.aiWorker.resources | nindent 12 }}
          volumeMounts:
            {{- include "nextcloud.volumeMounts" . | trim | nindent 12 }}
      volumes:
        {{- include "nextcloud.volumes" . | trim | nindent 8 }}
      restartPolicy: Always
{{- end }}
