{{- if .Values.nextcloud.phpConfigs -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nextcloud.fullname" . }}-phpconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels"  ( dict "rootContext" $ ) | nindent 4 }}
data:
  {{- range $key, $value := .Values.nextcloud.phpConfigs }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
