{{- if .Values.route.enabled }}
apiVersion: {{ .Values.route.apiVersion }}
kind: {{ .Values.route.kind }}
metadata:
  name: {{ template "nextcloud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels"  ( dict "component" "app"  "rootContext" $ ) | nindent 4 }}
    {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- with .Values.route.additionalRules }}
    {{- tpl (toYaml .Values.route.additionalRules) $ | nindent 4 }}
    {{- end }}
    - backendRefs:
        - name: {{ template "nextcloud.fullname" . }}
          port: {{ .Values.service.port }}
      {{- with .Values.route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.route.matches }}
      matches:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- end }}
