fullnameOverride: nextcloud

nextcloud:
  host: "ingress-nginx-controller.ingress-nginx.svc"
  trustedDomains:
    - 'nextcloud.nextcloud.svc.cluster.local'
    - 'ingress-nginx-controller.ingress-nginx.svc'
    - 'nextcloud'

ingress:
  enabled: true

redis:
  enabled: true

internalDatabase:
  enabled: false
mariadb:
  enabled: true

notifyPush:
  enabled: true
  autoSetup: true
