{{- if .Values.metrics.enabled }}
{{- with .Values.metrics.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nextcloud.fullname" $ }}-metrics
  labels:
    {{- include "nextcloud.labels"  ( dict "component" "metrics"  "rootContext" $ ) | nindent 4 }}
    app.kubernetes.io/monitor: enabled
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  {{- if eq .type "LoadBalancer" }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "nextcloud.selectorLabels"  ( dict "component" "metrics"  "rootContext" $ ) | nindent 4 }}
  ports:
    - name: http
      port: 9100
      targetPort: metrics
{{- end }}
{{- end }}
