apiVersion: v2
name: nextcloud
version: 2.12.1
appVersion: 22.2.3
description: A file sharing server that puts the control and security of your own data back into your hands.
keywords:
- nextcloud
- storage
- http
- web
- php
home: https://nextcloud.com/
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
sources:
- https://github.com/nextcloud/helm
- https://github.com/nextcloud/docker
maintainers:
- name: skjnldsv
  email: skjnldsv@protonmail.com
- name: chrisingenhaag
  email: christian.ingenhaag@googlemail.com
- name: billimek
  email: jeff@billimek.com
dependencies:
- name: postgresql
  version: 10.13.*
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: mariadb
  version: 9.8.*
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
- name: redis
  version: 15.6.*
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
