apiVersion: v2
name: nextcloud
version: 5.3.1
appVersion: 29.0.4
description: A file sharing server that puts the control and security of your own data back into your hands.
keywords:
  - nextcloud
  - storage
  - http
  - web
  - php
home: https://nextcloud.com/
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
sources:
  - https://github.com/nextcloud/helm
  - https://github.com/nextcloud/docker
maintainers:
  - name: skjnldsv
    email: skjnldsv@protonmail.com
  - name: chrisingenhaag
    email: christian.ingenhaag@googlemail.com
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: postgresql
    version: 15.5.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: mariadb
    version: 18.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: 19.5.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
