apiVersion: v2
name: nextcloud
version: 7.1.0
# renovate: image=docker.io/library/nextcloud
appVersion: 31.0.8
description: A file sharing server that puts the control and security of your own data back into your hands.
keywords:
  - nextcloud
  - storage
  - http
  - web
  - php
home: https://nextcloud.com/
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
sources:
  - https://github.com/nextcloud/helm
  - https://github.com/nextcloud/docker
maintainers:
  - name: skjnldsv
    email: skjnldsv@protonmail.com
  - name: chrisingenhaag
    email: christian.ingenhaag@googlemail.com
  - name: billimek
    email: jeff@billimek.com
  - name: WrenIX
    url: https://wrenix.eu
  - name: jessebot
    url: https://jessebot.work
dependencies:
  - name: postgresql
    version: 16.7.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: mariadb
    version: 20.5.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: 21.1.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: collabora-online
    version: 1.1.20
    repository: https://collaboraonline.github.io/online
    condition: collabora.enabled
    alias: collabora
